# Generated by Django 3.2.6 on 2021-09-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bienes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('num_unidades', models.PositiveIntegerField()),
                ('num_cajas', models.PositiveIntegerField()),
                ('lote', models.CharField(max_length=12)),
                ('caducidad', models.DateField()),
                ('tipo_bienes', models.CharField(max_length=3)),
                ('codigo_barras', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
