# Generated by Django 3.2.6 on 2021-09-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienes',
            name='tipo_bienes',
            field=models.CharField(choices=[('INS', 'Insumo'), ('MED', 'Medicamento')], max_length=3),
        ),
    ]
