# Generated by Django 3.2.6 on 2021-10-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0002_alter_bienes_tipo_bienes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienes',
            name='codigo_barras',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
