# Generated by Django 3.2.6 on 2021-10-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0003_alter_bienes_codigo_barras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bienes',
            name='codigo_barras',
        ),
    ]
