# Generated by Django 3.2.6 on 2021-11-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0004_remove_bienes_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienes',
            name='codigo_barras',
            field=models.CharField(default='000000000000', max_length=12, unique=True),
        ),
    ]
