# Generated by Django 3.2.6 on 2021-09-25 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bienes', '0002_alter_bienes_tipo_bienes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bienes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes.bienes')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
