# Generated by Django 3.2.6 on 2021-11-27 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='hora',
        ),
    ]
