# Generated by Django 3.2.6 on 2021-11-28 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('bitacoras', '0002_auto_20211126_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='usuario',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado'),
            preserve_default=False,
        ),
    ]
