# Generated by Django 3.2.6 on 2021-11-29 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0003_auto_20211128_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='area',
        ),
    ]
