# Generated by Django 3.2.6 on 2021-11-29 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0004_remove_bitacora_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='receta',
        ),
    ]
